// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6QIFHaWbuV4b90UkhtFuHKoNkqxiDOCU',
    appId: '1:48081242628:web:341842959db48d4df98351',
    messagingSenderId: '48081242628',
    projectId: 'snow-daze',
    authDomain: 'snow-daze.firebaseapp.com',
    storageBucket: 'snow-daze.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRlt6lvJm7qAbndalRHqp92vR9kydZrus',
    appId: '1:48081242628:android:b56c1d80737885b2f98351',
    messagingSenderId: '48081242628',
    projectId: 'snow-daze',
    storageBucket: 'snow-daze.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsHq0Bl5VU65sBv-uDdbbhDK4EWRRPi0c',
    appId: '1:48081242628:ios:906145cddbffac94f98351',
    messagingSenderId: '48081242628',
    projectId: 'snow-daze',
    storageBucket: 'snow-daze.appspot.com',
    iosClientId: '48081242628-rgustl1mj87d380dpg70k11ob5r5t44d.apps.googleusercontent.com',
    iosBundleId: 'com.example.snowDaze',
  );
}
